### PR TITLE
refactor: update package names

### PR DESCRIPTION
**Pull request by ramey**
Change package names throughout Raccoon to more standard naming, which includes `directory/user`

Eg - `raccoon/config` -> `github.com/odpf/raccoon`

Signed-off-by: ramey <rameygirdhar@gmail.com>

### CODE REVIEW

**Review by chakravarthyvp — APPROVED** [review]
LGTM

**Comment by chakravarthyvp** [comment]
```
Signed-off-by: ramey [rameygirdhar@gmail.com](mailto:rameygirdhar@gmail.com)
```
Why do we need this sign-off? Is it part of our template?

**Comment by ramey** [comment]
> ```
> Signed-off-by: ramey [rameygirdhar@gmail.com](mailto:rameygirdhar@gmail.com)
> ```
> 
> Why do we need this sign-off? Is it part of our template?

@chakravarthyvp  It's just something I am used to doing, seen this in a lot of Open source projects. Do we have any template as such?

**Comment by chakravarthyvp** [comment]
> @chakravarthyvp It's just something I am used to doing, seen this in a lot of Open source projects. Do we have any template as such?

You can refer here. We follow conventional commits and don't need explicit sign-off.
https://github.com/odpf/raccoon/blob/main/docs/contribute/development.md

**Pull request merged**
